"""empty message

Revision ID: b26ecfebe7a9
Revises: 55454a92f041
Create Date: 2018-03-15 10:17:57.809162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26ecfebe7a9'
down_revision = '55454a92f041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetup', sa.Column('pacou', sa.String(), nullable=True))
    op.drop_column('meetup', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetup', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('meetup', 'pacou')
    # ### end Alembic commands ###
