"""empty message

Revision ID: d9bbf674674f
Revises: b26ecfebe7a9
Create Date: 2018-03-15 10:18:16.275340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9bbf674674f'
down_revision = 'b26ecfebe7a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetup', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('meetup', 'pacou')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetup', sa.Column('pacou', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('meetup', 'title')
    # ### end Alembic commands ###
